/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "selector",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/_lib/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                poppins: ["Poppins", "sans-serif"],
            },
            fontWeight: {
                thin: 100,
                extralight: 200,
                light: 300,
                regular: 400,
                medium: 500,
                semibold: 600,
                bold: 700,
                extrabold: 800,
                black: 900,
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "gradient-conic":
                    "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
            },
            boxShadow: {
                outer: "0px 0px 60px 20px rgba(0, 0, 0, 0.3)",
                around: "0 1px 15px 7px rgba(0, 0, 0, 0.35)",
                "around-sm": "0 1px 8px 3px rgba(0, 0, 0, 0.35)",
                "around-md": "0 1px 11px 5px rgba(0, 0, 0, 0.35)",
                "around-lg": "0 1px 18px 10px rgba(0, 0, 0, 0.35)",
                "around-xl": "0 1px 23px 13px rgba(0, 0, 0, 0.35)",
            },
            colors: {
                "light-bg": "#f0f0f0",
                "dark-bg": "#141414",
                gold: {
                    DEFAULT: "#d4af37",
                },
                silver: {
                    DEFAULT: "#a5a9b4",
                },
                bronze: {
                    DEFAULT: "#ce8946",
                },
                background: {
                    DEFAULT: "var(--background)",
                    10: "var(--background-10)",
                    20: "var(--background-20)",
                    30: "var(--background-30)",
                    40: "var(--background-40)",
                    50: "var(--background-50)",
                    60: "var(--background-60)",
                    70: "var(--background-70)",
                    80: "var(--background-80)",
                    90: "var(--background-90)",
                },
                text: {
                    DEFAULT: "var(--text)",
                    10: "var(--text-10)",
                    20: "var(--text-20)",
                    30: "var(--text-30)",
                    40: "var(--text-40)",
                    50: "var(--text-50)",
                    60: "var(--text-60)",
                    70: "var(--text-70)",
                    80: "var(--text-80)",
                    90: "var(--text-90)",
                },
                primary: {
                    DEFAULT: "var(--primary)",
                    10: "var(--primary-10)",
                    20: "var(--primary-20)",
                    30: "var(--primary-30)",
                    40: "var(--primary-40)",
                    50: "var(--primary-50)",
                    60: "var(--primary-60)",
                    70: "var(--primary-70)",
                    80: "var(--primary-80)",
                    90: "var(--primary-90)",
                },
                secondary: {
                    DEFAULT: "var(--secondary)",
                    10: "var(--secondary-10)",
                    20: "var(--secondary-20)",
                    30: "var(--secondary-30)",
                    40: "var(--secondary-40)",
                    50: "var(--secondary-50)",
                    60: "var(--secondary-60)",
                    70: "var(--secondary-70)",
                    80: "var(--secondary-80)",
                    90: "var(--secondary-90)",
                },
                accent: {
                    DEFAULT: "var(--accent)",
                    10: "var(--accent-10)",
                    20: "var(--accent-20)",
                    30: "var(--accent-30)",
                    40: "var(--accent-40)",
                    50: "var(--accent-50)",
                    60: "var(--accent-60)",
                    70: "var(--accent-70)",
                    80: "var(--accent-80)",
                    90: "var(--accent-90)",
                },
            },
        },
    },
    plugins: [],
    corePlugins: {
        pointerEvents: true,
    },
};
